
package presentation.binding;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EndpointInterface", targetNamespace = "http://soap.server.integration/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EndpointInterface {


    /**
     * 
     * @param month
     * @param year
     * @param id
     * @return
     *     returns presentation.binding.UserCaloriesResponse
     */
    @WebMethod
    @WebResult(name = "calories", targetNamespace = "")
    @RequestWrapper(localName = "getUserCalories", targetNamespace = "http://soap.server.integration/", className = "presentation.binding.GetUserCalories")
    @ResponseWrapper(localName = "getUserCaloriesResponse", targetNamespace = "http://soap.server.integration/", className = "presentation.binding.GetUserCaloriesResponse")
    @Action(input = "http://soap.server.integration/EndpointInterface/getUserCaloriesRequest", output = "http://soap.server.integration/EndpointInterface/getUserCaloriesResponse")
    public UserCaloriesResponse getUserCalories(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "year", targetNamespace = "")
        String year,
        @WebParam(name = "month", targetNamespace = "")
        String month);

    /**
     * 
     * @param id
     * @return
     *     returns presentation.binding.UserDevicesResponse
     */
    @WebMethod
    @WebResult(name = "devices", targetNamespace = "")
    @RequestWrapper(localName = "getUserDevices", targetNamespace = "http://soap.server.integration/", className = "presentation.binding.GetUserDevices")
    @ResponseWrapper(localName = "getUserDevicesResponse", targetNamespace = "http://soap.server.integration/", className = "presentation.binding.GetUserDevicesResponse")
    @Action(input = "http://soap.server.integration/EndpointInterface/getUserDevicesRequest", output = "http://soap.server.integration/EndpointInterface/getUserDevicesResponse")
    public UserDevicesResponse getUserDevices(
        @WebParam(name = "id", targetNamespace = "")
        String id);

}
